login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.loginUser.as_view(), name="loginUser"),
]

quanlythietbisite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("register.urls")),
    path("login/", include("login.urls")),
    path("thietbi/", include("thietbi.urls")),
]

register/urls.py
from django.urls import path
from . import views

app_name = "register"
urlpatterns = [
    path("", views.registerUser.as_view(), name="registerUsser"),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms

class loginForm(forms.Form):
    tendangnhap = forms.CharField(max_length=50, label='Tên đăng nhập')
    matkhau = forms.CharField(widget=forms.PasswordInput, label='Mật khẩu')

login/views.py
from django.shortcuts import render
from .forms import loginForm
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.shortcuts import redirect

# Create your views here.
class loginUser(View):
    def get(self, request):
        lF = loginForm
        return render(request, "login/login.html", {"lF": lF})
    def post(self, request):
        if request.method == 'POST':
            lF = loginForm(request.POST)
            tendangnhap = request.POST["tendangnhap"]
            matkhau = request.POST["matkhau"]
            user = authenticate(request, username = tendangnhap, password = matkhau)
            if user is not None:
                login(request, user)
                thietbi_url = reverse('thietbi:index')
                return redirect(thietbi_url)
            else:
                lF.add_error('tendangnhap', 'Tên đăng nhập hoặc mật khẩu không hợp lệ')
        else:
            form = loginForm()
        return render(request, "login/login.html", {'lF': lF})

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
</head>
<body>
    <div class="background"></div>
    <div class="form-register">
        <div class="box">
            <h2>ĐĂNG NHẬP</h2>
            <form action="{% url 'login:loginUser' %}" method="post">
                {% csrf_token %}
                {{ lF.as_p }}
                {% if lF.errors %}
                    <ul class="error-list">
                        {% for field, errors in lF.errors.items %}
                            {% for error in errors %}
                                <li><span class="error-message">{{ error }}</span></li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
                <input type="submit" value="ĐĂNG NHẬP">
                <p>Bạn chưa có tài khoản <a href="{% url 'register:registerUsser' %}">Đăng ký</a></p>
            </form>
        </div>
    </div>
    <div class="logo">
        <div class="box">
            <img src="{% static 'login/img/Ellipse3.png' %}" alt="Ellipse3">
            <div class="text">
                <p>P&S</p>
                <br>
                <p>Quản lý thiết bị</p>
            </div>
        </div>
    </div>
</body>
</html>