login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.loginUser.as_view(), name="loginUser"),
]

quanlythietbisite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("register.urls")),
    path("login/", include("login.urls")),
    path("thietbi/", include("thietbi.urls")),
]

thietbi/urls.py
from django.urls import path
from . import views

app_name = "thietbi"
urlpatterns = [
    path("", views.index, name="index"),
    path("themthietbi/", views.themthietbi.as_view(), name="themthietbi"),
    path("chitietthietbi/<int:id>/", views.chitietthietbi.as_view(), name="chitietthietbi"),
    path("xoathietbi/<int:id>/", views.xoathietbi, name="xoathietbi"),
    path("loai/", views.loai, name="loai"),
    path("loai/themloai/", views.themloai.as_view(), name="themloai"),
    path("loai/<int:id>/", views.getThietBiTheoLoai, name="thietbitheoloai"),
    path("loai/chitietloai/<int:id>/", views.chitietloai.as_view(), name="chitietloai"),
    path("loai/xoaloai/<int:id>/", views.xoaloai, name="xoaloai"),
    path("phong/", views.phong, name="phong"),
    path("phong/themphong/", views.themphong.as_view(), name="themphong"),
    path("phong/<int:id>/", views.getThietBiTheoPhong, name="thietbitheophong"),
    path("phong/chitietphong/<int:id>/", views.chitietphong.as_view(), name="chitietphong"),
    path("phong/xoaphong/<int:id>/", views.xoaphong, name="xoaphong"),
    path("nhacungcap/", views.nhacungcap, name="nhacungcap"),
    path("nhacungcap/themnhacungcap/", views.themnhacungcap.as_view(), name="themnhacungcap"),
    path("nhacungcap/<int:id>/", views.getThietBiTheoNhaCungCap, name="thietbitheonhacungcap"),
    path("nhacungcap/chitietnhacungcap/<int:id>/", views.chitietnhacungcap.as_view(), name="chitietnhacungcap"),
    path("nhacungcap/xoanhacungcap/<int:id>/", views.xoanhacungcap, name="xoanhacungcap"),
    path("searchthietbi/", views.searchthietbi, name="searchthietbi"),
    path("sortthietbi/", views.sortthietbi, name="sortthietbi"),
    path("dangxuat/", views.dangxuat, name="dangxuat"),
    path("chitietnguoidung/", views.chitietnguoidung.as_view(), name="chitietnguoidung"),
    path('locthietbitheogia/', views.locThietBiTheoGia, name='locthietbitheogia'),
    path('locthietbitheobaohanh/', views.locThietBiTheoBaoHanh, name='locthietbitheobaohanh'),
    path('dash-data/', views.dash_data, name='dash_data'),
    path('dash-chart/', views.dash_chart, name='dash_chart'),
    path('dash-data2/', views.dash_data2, name='dash_data2'),
]

thietbi/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class LOAI(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    tenloai = models.CharField(max_length=100, default="Chưa xác định tên loại!", unique=True)
    mota = models.TextField(default="", blank=True, null=True)
    
    def __str__(self):
        return f"{self.tenloai}"
    
class PHONG(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    tenphong = models.CharField(max_length=100, default="Chưa xác định tên phòng!", unique=True)
    sotang = models.IntegerField(default=0)
    mota = models.TextField(default="", blank=True, null=True)
    
    def __str__(self):
        return f"{self.tenphong}"
    
class NHACUNGCAP(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    tennhacungcap = models.CharField(max_length=100, default="Chưa xác định tên nhà cung cấp!", unique=True)
    diachi = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(default='example@emailx.com', null=True, blank=True)
    sodienthoai = models.CharField(max_length=15, null=True, blank=True)
    mota = models.TextField(default="", blank=True, null=True)
    
    def __str__(self):
        return f"{self.tennhacungcap}"
    
class THIETBI(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    tenloai = models.ForeignKey(LOAI, on_delete=models.CASCADE)
    tenphong = models.ForeignKey(PHONG, on_delete=models.CASCADE)
    tennhacungcap = models.ForeignKey(NHACUNGCAP, on_delete=models.CASCADE)
    tenthietbi = models.CharField(max_length=100, default="Chưa xác định tên thiết bị!", unique=True)
    giamua = models.IntegerField(default=0)
    ngaythem = models.DateTimeField(auto_now_add=True)
    ngaymua = models.DateTimeField(default=datetime.now())
    ngayhethanbaohanh = models.DateTimeField(default=datetime.now())
    ngaykiemtradinhky = models.DateTimeField(default=datetime.now())
    
    TEN_tinhtrang_CHOICES = (
        ('tinhtrang1', 'Bình thường'),
        ('tinhtrang2', 'Đang hỏng'),
        ('tinhtrang3', 'Đang sửa'),
    )
    tinhtrang = models.CharField(max_length=255, choices=TEN_tinhtrang_CHOICES, default='tinhtrang1')
    mota = models.TextField(default="", blank=True, null=True)
    
    def __str__(self):
        return f"{self.tenthietbi}"

thietbi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import formLoai, formPhong,formThietbi, formNhaCungCap, formChiTietLoai, formChiTietPhong, formChiTietNhaCungCap, formChiTietNguoiDung, formLocThietBiTheoGia
from django.views import View
from .models import LOAI, PHONG, NHACUNGCAP, THIETBI
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib.auth import logout
from register.models import NGUOIDUNG
from datetime import datetime, date
from django.http import JsonResponse
from django.db import models
from django.db.models import Sum
import re
# Create your views here.
@login_required(login_url='/login/')
def index(request):
    nguoi_dung = request.user
    thietbi_list = THIETBI.objects.filter(nguoi_dung=nguoi_dung)
    return render(request, "thietbi/thietbi.html", {"thietbi_list": thietbi_list})
                
@login_required(login_url='/login/')
def loai(request):
    nguoi_dung = request.user
    loai_list = LOAI.objects.filter(nguoi_dung=nguoi_dung)
    return render(request, "thietbi/loai.html", {"loai_list": loai_list})

@login_required(login_url='/login/')
def phong(request):
    nguoi_dung = request.user
    phong_list = PHONG.objects.filter(nguoi_dung=nguoi_dung)
    return render(request, "thietbi/phong.html", {"phong_list": phong_list})

@login_required(login_url='/login/')
def nhacungcap(request):
    nguoi_dung = request.user
    nhacungcap_list = NHACUNGCAP.objects.filter(nguoi_dung=nguoi_dung)
    return render(request, "thietbi/nhacungcap.html", {"nhacungcap_list": nhacungcap_list})

@login_required(login_url='/login/') 
def getThietBiTheoLoai(request, id):
    thietbi_list = THIETBI.objects.filter(tenloai=id)
    loai = LOAI.objects.get(id = id)
    return render(request, "thietbi/thietbi_loai.html", {"thietbi_list": thietbi_list, "loai": loai})
    
@login_required(login_url='/login/') 
def getThietBiTheoPhong(request, id):
    thietbi_list = THIETBI.objects.filter(tenphong=id)
    phong = PHONG.objects.get(id = id)
    return render(request, "thietbi/thietbi_phong.html", {"thietbi_list": thietbi_list, "phong": phong})

@login_required(login_url='/login/') 
def getThietBiTheoNhaCungCap(request, id):
    thietbi_list = THIETBI.objects.filter(tennhacungcap=id)
    nhacungcap = NHACUNGCAP.objects.get(id = id)
    return render(request, "thietbi/thietbi_nhacungcap.html", {"thietbi_list": thietbi_list, "nhacungcap": nhacungcap})
    
class themthietbi(LoginRequiredMixin, View):
    login_url='/login/'
    
    def get(self, request):
        fL = formThietbi()
        context = {"fL": fL}
        return render(request, "thietbi/themthietbi.html", context)
    
    def post(self, request):
        if request.method == "POST":
            fL = formThietbi(request.POST)
            if fL.is_valid():
                nguoi_dung = request.user
                tenloai = fL.cleaned_data["tenloai"]
                tenphong = fL.cleaned_data["tenphong"]
                tennhacungcap = fL.cleaned_data["tennhacungcap"]
                tenthietbi = fL.cleaned_data["tenthietbi"]
                giamua = fL.cleaned_data["giamua"]
                ngaymua = fL.cleaned_data["ngaymua"]
                ngayhethanbaohanh = fL.cleaned_data["ngayhethanbaohanh"]
                ngaykiemtradinhky = fL.cleaned_data["ngaykiemtradinhky"]
                tinhtrang = fL.cleaned_data["tinhtrang"]
                mota = fL.cleaned_data["mota"]
                
                if giamua < 0:  # Kiểm tra giá nhập không âm
                    fL.add_error('giamua', 'Giá nhập không được âm')
                elif ngayhethanbaohanh < ngaymua:  # Kiểm tra ngày hết hạn bảo hành không được hết hạn trước ngày mua
                    fL.add_error('ngayhethanbaohanh', 'Ngày hết hạn bảo hành không được hết hạn trước ngày mua')
                else:
                    if THIETBI.objects.filter(tenthietbi=tenthietbi).exists():
                        fL.add_error('tenthietbi', 'Tên thiết bị đã tồn tại')
                    else:
                        savefL = THIETBI(nguoi_dung=nguoi_dung, tenloai=tenloai, tenphong=tenphong, tennhacungcap=tennhacungcap, 
                                         tenthietbi=tenthietbi, giamua=giamua, ngaymua=ngaymua, ngayhethanbaohanh=ngayhethanbaohanh, 
                                         ngaykiemtradinhky=ngaykiemtradinhky, tinhtrang=tinhtrang, mota=mota)
                        savefL.save()
                        messages.info(request, 'Thêm thành công')
        else:
            fL = formThietbi()
        
        return render(request, "thietbi/themthietbi.html", {'fL': fL})


class themloai(LoginRequiredMixin, View):
    login_url='/login/'
    def get(self, request):
        fL = formLoai
        context = {"fL": fL}
        return render(request, "thietbi/themloai.html", context)
    
    def post(self, request):
        if request.method == "POST":
            fL = formLoai(request.POST)
            if fL.is_valid():
                nguoi_dung = request.user
                tenloai = fL.cleaned_data["tenloai"]
                mota = fL.cleaned_data["mota"]
                if LOAI.objects.filter(tenloai=tenloai).exists():
                    fL.add_error('tenloai', 'Tên loại đã tồn tại')
                else:
                    savefL = LOAI(nguoi_dung=nguoi_dung, tenloai=tenloai, mota=mota)
                    savefL.save()
                    messages.info(request, 'Thêm thành công')
        else:
            fL = formLoai()
        return render(request, "thietbi/themloai.html", {'fL': fL})

class themphong(LoginRequiredMixin, View):
    login_url='/login/'
    def get(self, request):
        fL = formPhong
        context = {"fL": fL}
        return render(request, "thietbi/themphong.html", context)
    
    def post(self, request):
        if request.method == "POST":
            fL = formPhong(request.POST)
            if fL.is_valid():
                nguoi_dung = request.user
                tenphong = fL.cleaned_data["tenphong"]
                sotang = fL.cleaned_data["sotang"]
                mota = fL.cleaned_data["mota"]
                if sotang < 0:  # Kiểm tra số tầng không âm
                    fL.add_error('sotang', 'Số tầng không được âm')
                elif PHONG.objects.filter(tenphong=tenphong).exists():
                    fL.add_error('tenphong', 'Tên phòng đã tồn tại')
                else:
                    savefL = PHONG(nguoi_dung=nguoi_dung, tenphong=tenphong, sotang=sotang, mota=mota)
                    savefL.save()
                    messages.info(request, 'Thêm thành công')
        else:
            fL = formPhong()
        return render(request, "thietbi/themphong.html", {'fL': fL})

    


class themnhacungcap(LoginRequiredMixin, View):
    login_url='/login/'
    def get(self, request):
        fL = formNhaCungCap
        context = {"fL": fL}
        return render(request, "thietbi/themnhacungcap.html", context)
    
    def post(self, request):
        if request.method == "POST":
            fL = formNhaCungCap(request.POST)
            if fL.is_valid():
                nguoi_dung = request.user
                tennhacungcap = fL.cleaned_data["tennhacungcap"]
                diachi = fL.cleaned_data["diachi"]
                email = fL.cleaned_data["email"]
                sodienthoai = fL.cleaned_data["sodienthoai"]
                mota = fL.cleaned_data["mota"]
                
                # Kiểm tra số điện thoại có đúng định dạng hay không
                if not re.match(r'^\d{10,11}$', sodienthoai):
                    fL.add_error('sodienthoai', 'Số điện thoại không hợp lệ')
                elif NHACUNGCAP.objects.filter(tennhacungcap=tennhacungcap, diachi=diachi, email=email, sodienthoai=sodienthoai).exists():
                    fL.add_error('tennhacungcap', 'Tên nhà cung cấp đã tồn tại')
                else:
                    savefL = NHACUNGCAP(nguoi_dung=nguoi_dung, tennhacungcap=tennhacungcap, diachi=diachi, email=email, sodienthoai=sodienthoai, mota=mota)
                    savefL.save()
                    messages.info(request, 'Thêm thành công')
        else:
            fL = formNhaCungCap()
        return render(request, "thietbi/themnhacungcap.html", {'fL': fL})

@login_required(login_url='/login/') 
def xoathietbi(request, id):
    thietbi = THIETBI.objects.get(id=id)
    thietbi.delete()
    return redirect("thietbi:index")

@login_required(login_url='/login/') 
def xoaloai(request, id):
    loai = LOAI.objects.get(id=id)
    loai.delete()
    return redirect("thietbi:loai")

@login_required(login_url='/login/') 
def xoaphong(request, id):
    phong = PHONG.objects.get(id=id)
    phong.delete()
    return redirect("thietbi:phong")

@login_required(login_url='/login/') 
def xoanhacungcap(request, id):
    nhacungcap = NHACUNGCAP.objects.get(id=id)
    nhacungcap.delete()
    return redirect("thietbi:nhacungcap")

class chitietthietbi(LoginRequiredMixin, View):
    login_url = '/login/'
    
    def get(self, request, id):
        thietbi = THIETBI.objects.get(id=id)
        form = formThietbi(instance=thietbi)
        return render(request, "thietbi/chitietthietbi.html", {"thietbi": thietbi, "form": form})
    
    def post(self, request, id):
        if 'xoa' in request.POST:
            try:
                thietbi = THIETBI.objects.get(id=id)
                thietbi.delete()
                messages.success(request, 'Xóa thiết bị thành công.')
                return redirect('thietbi:index')
            except THIETBI.DoesNotExist:
                messages.error(request, 'Thiết bị không tồn tại.')
                return redirect('thietbi:index')
        else:
            if request.method == "POST":
                thietbi = THIETBI.objects.get(id=id)
                form = formThietbi(request.POST, instance=thietbi)

thietbi/templates/thietbi/chitietloai.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'thietbi/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'thietbi/css/bootstrap.min.css' %}">
    <script src="{% static 'thietbi/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'thietbi/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>
    <div class="app">
        <div class="logo">
            <img src="{% static 'thietbi/img/Ellipse3.png' %}" alt="Ellipse3">
            <p>P&S</p>
            <br>
            <p>Quản lý thiết bị</p>
        </div>
        <div class="header">
            <a href="{% url 'thietbi:dangxuat' %}">
                <button class="dangxuat" type="submit">Đăng xuất</button>
            </a>
        </div>
        <div class="menu">
            <a href="{% url 'thietbi:chitietnguoidung' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Tài khoản</p>
                </div>
            </a>
            <a href="{% url 'thietbi:index' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle12.png' %}" alt="Rectangle12">
                    <p>Thiết bị</p>
                </div>
            </a>
            <a href="{% url 'thietbi:locthietbitheogia' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Phân tích</p>
                </div>
            </a>
            <a href="{% url 'thietbi:dash_chart' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle14.png' %}" alt="Rectangle14">
                    <p>Thống kê</p>
                </div>
            </a>
        </div>
        <div class="content">
            <h2 class="text-center">CHI TIẾT LOẠI: {{ loai.tenloai }}</h2>
            <form method="POST" action="{% url 'thietbi:chitietloai' loai.id %}">
                {% csrf_token %}
                {{ form.as_p }} 
                {% if fL.errors %}
                    <ul class="error-list">
                        {% for field, errors in fL.errors.items %}
                            {% for error in errors %}
                                <li><span class="error-message">{{ error }}</span></li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <button type="submit">Lưu</button>
            </form>
            <form class="xoa-form" method="POST" action="{% url 'thietbi:xoaloai' loai.id %}">
                {% csrf_token %}
                <button class="delete" type="button" onclick="confirmDelete()">Xóa</button>
            </form>
            <a href="{% url 'thietbi:loai' %}">
                <button class="back" type="submit">Quay lại</button>
            </a>
        </div>
    </div>
    <script>
        document.querySelector('.delete').addEventListener('click', function() {
            if (confirm('Bạn có chắc chắn muốn xóa loại này?')) {
                document.querySelector('.xoa-form').submit();
            }
        });
    </script>
</body>
</html>

thietbi/templates/thietbi/chitietphong.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'thietbi/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'thietbi/css/bootstrap.min.css' %}">
    <script src="{% static 'thietbi/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'thietbi/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>
    <div class="app">
        <div class="logo">
            <img src="{% static 'thietbi/img/Ellipse3.png' %}" alt="Ellipse3">
            <p>P&S</p>
            <br>
            <p>Quản lý thiết bị</p>
        </div>
        <div class="header">
            <a href="{% url 'thietbi:dangxuat' %}">
                <button class="dangxuat" type="submit">Đăng xuất</button>
            </a>
        </div>
        <div class="menu">
            <a href="{% url 'thietbi:chitietnguoidung' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Tài khoản</p>
                </div>
            </a>
            <a href="{% url 'thietbi:index' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle12.png' %}" alt="Rectangle12">
                    <p>Thiết bị</p>
                </div>
            </a>
            <a href="{% url 'thietbi:locthietbitheogia' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Phân tích</p>
                </div>
            </a>
            <a href="{% url 'thietbi:dash_chart' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle14.png' %}" alt="Rectangle14">
                    <p>Thống kê</p>
                </div>
            </a>
        </div>
        <div class="content">
            <h2 class="text-center">CHI TIẾT PHÒNG: {{ phong.tenphong }}</h2>
            <form method="POST" action="{% url 'thietbi:chitietphong' phong.id %}">
                {% csrf_token %}
                {{ form.as_p }} 
                {% if fL.errors %}
                    <ul class="error-list">
                        {% for field, errors in fL.errors.items %}
                            {% for error in errors %}
                                <li><span class="error-message">{{ error }}</span></li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <button type="submit">Lưu</button>
            </form>
            <form class="xoa-form" method="POST" action="{% url 'thietbi:xoaphong' phong.id %}">
                {% csrf_token %}
                <button class="delete" type="button" onclick="confirmDelete()">Xóa</button>
            </form>
            <a href="{% url 'thietbi:phong' %}">
                <button class="back" type="submit">Quay lại</button>
            </a>
        </div>
    </div>
    <script>
        document.querySelector('.delete').addEventListener('click', function() {
            if (confirm('Bạn có chắc chắn muốn xóa phòng này?')) {
                document.querySelector('.xoa-form').submit();
            }
        });
    </script>
</body>
</html>

thietbi/templates/thietbi/chitietthietbi.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'thietbi/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'thietbi/css/bootstrap.min.css' %}">
    <script src="{% static 'thietbi/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'thietbi/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>
    <div class="app">
        <div class="logo">
            <img src="{% static 'thietbi/img/Ellipse3.png' %}" alt="Ellipse3">
            <p>P&S</p>
            <br>
            <p>Quản lý thiết bị</p>
        </div>
        <div class="header">
            <a href="{% url 'thietbi:dangxuat' %}">
                <button class="dangxuat" type="submit">Đăng xuất</button>
            </a>
        </div>
        <div class="menu">
            <a href="{% url 'thietbi:chitietnguoidung' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Tài khoản</p>
                </div>
            </a>
            <a href="{% url 'thietbi:index' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle12.png' %}" alt="Rectangle12">
                    <p>Thiết bị</p>
                </div>
            </a>
            <a href="{% url 'thietbi:locthietbitheogia' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle16.png' %}" alt="Rectangle16">
                    <p>Phân tích</p>
                </div>
            </a>
            <a href="{% url 'thietbi:dash_chart' %}">
                <div class="task1">
                    <img src="{% static 'thietbi/img/Rectangle14.png' %}" alt="Rectangle14">
                    <p>Thống kê</p>
                </div>
            </a>
        </div>
        <div class="content">
            <h2 class="text-center">CHI TIẾT THIẾT BỊ: {{ thietbi.tenthietbi }}</h2>
            <form method="POST" action="{% url 'thietbi:chitietthietbi' thietbi.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <p class="ngaythem">Ngày thêm: {{ thietbi.ngaythem }}</p>
                {% if fL.errors %}
                    <ul class="error-list">
                        {% for field, errors in fL.errors.items %}
                            {% for error in errors %}
                                <li><span class="error-message">{{ error }}</span></li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <button type="submit">Lưu</button>
            </form>
            <form class="xoa-form" method="POST" action="{% url 'thietbi:xoathietbi' thietbi.id %}">
                {% csrf_token %}
                <button class="delete" type="button" onclick="confirmDelete()">Xóa</button>
            </form>
            <a href="{% url 'thietbi:index' %}">
                <button class="back" type="submit">Quay lại</button>
            </a>
        </div>
    </div>
    <script>
        document.querySelector('.delete').addEventListener('click', function() {
            if (confirm('Bạn có chắc chắn muốn xóa thiết bị này?')) {
                document.querySelector('.xoa-form').submit();
            }
        });
    </script>
</body>
</html>